HOST: http://api.monty-repo.org/

--- REST API v1 ---
---
Welcome to our API documentation of Monty. This API offers you all functions which are included on http://www.monty-repo.org/ and the command line interface.
---

--
Authentication
--

--
Profiles
This section explains you to handle with profiles.
--
List products added into your shopping-cart. (comment block again in Markdown)
GET /user/:email@example.com
< 200
< Content-Type: application/json
{
    "username":"example",
    "email":"email@example.com",
    "status":true
}


Create new user / Register
Mandatory fields are checked as follows:
    username: ASCII chars and at least one char
    password: All chars and at least 8 chars
    email: valid email syntax
PUT /user
> Accept: application/json
> Content-Type: application/json
{
    "username": "user"
    "password": "plain_password"
    "email": "your@email.com"
}
< 201
< Content-Type: application/json
{
    "code": "OK"
}
+++++
< 400
< Content-Type: application/json
{
    "code": "UserError",
    "message": "Invalid*"
}
+++++
< 409
< Content-Type: application/json
{
    "code": "DuplicateEntryError",
    "message": "Email address already in use."
}
